Download from alpha source if dist contains "alpha"

diff --git a/neoget b/neoget
--- a/neoget
+++ b/neoget
@@ -82,13 +82,19 @@ function download {
         fi
         if [ $DOWNLOAD -eq 1 ]
         then
-            curl --silent --fail "${DIST}/${ARCHIVE}" -o "${ARCHIVE}"
+            if [[ "${VERSION}" == *"alpha"* ]]
+            then
+                URL="${ALPHA}/${ARCHIVE}"
+            else
+                URL="${DIST}/${ARCHIVE}"
+            fi
+            curl --silent --fail "${URL}" -o "${ARCHIVE}"
             RESULT=$?
             if [ $RESULT -eq 0 ]
             then
                 echo "${ARCHIVE}"
             else
-                echo 1>&2 "Cannot download archive ${DIST}/${ARCHIVE}"
+                echo 1>&2 "Cannot download archive ${URL}"
                 exit $RESULT
             fi
         else
@@ -101,7 +107,6 @@ while getopts ":acdefhluvx" OPTION
 do
   case ${OPTION} in
     a)
-      DIST="${ALPHA}"
       ALL_VERSIONS="3.0.0-alpha.LATEST"
       ;;
     c)
